package com.example.countries;

import java.util.ArrayList;
import java.util.List;
import java.util.LinkedHashMap;

public class ExpandableListDataPump {

    public static LinkedHashMap<String,List<String>> getData(){
        LinkedHashMap<String,List<String>> expandableListDetail = new LinkedHashMap<String,List<String>>();

        List<String> africa = new ArrayList<String>();
        africa.add("Algeria");
        africa.add("Angola");
        africa.add("Benin");
        africa.add("Botswana");
        africa.add("Burkina_Faso");
        africa.add("Burundi");
        africa.add("Cameroon");
        africa.add("Cape_Verde");
        africa.add("Central_African_Republic");
        africa.add("Chad");
        africa.add("Comoros");
        africa.add("Dem._Rep._of_the_Congo");
        africa.add("Djibouti");
        africa.add("Egypt");
        africa.add("Eq._Guinea");
        africa.add("Eritrea");
        africa.add("Ethiopia");
        africa.add("Gabon");
        africa.add("Gambia");
        africa.add("Ghana");
        africa.add("Guinea");
        africa.add("Guinea_Bissau");
        africa.add("Ivory_Coast");
        africa.add("Kenya");
        africa.add("Lesotho");
        africa.add("Liberia");
        africa.add("Libya");
        africa.add("Madagascar");
        africa.add("Malawi");
        africa.add("Mali");
        africa.add("Mauritania");
        africa.add("Mauritius");
        africa.add("Morocco");
        africa.add("Mozambique");
        africa.add("Namibia");
        africa.add("Niger");
        africa.add("Nigeria");
        africa.add("Republic_of_the_Congo");
        africa.add("Rwanda");
        africa.add("Sao_Tome");
        africa.add("Senegal");
        africa.add("Seychelles");
        africa.add("Sierra_Leone");
        africa.add("Somalia");
        africa.add("South_Africa");
        africa.add("Sudan");
        africa.add("Swaziland");
        africa.add("Tanzania");
        africa.add("Togo");
        africa.add("Tunisia");
        africa.add("Uganda");
        africa.add("Zambia");
        africa.add("Zimbabwe");

        List<String> asia = new ArrayList<String>();
        asia.add("Afghanistan");
        asia.add("Armenia");
        asia.add("Azerbaijan");
        asia.add("Bahrain");
        asia.add("Bangladesh");
        asia.add("Bhutan");
        asia.add("Brunei");
        asia.add("Cambodia");
        asia.add("China");
        asia.add("Christmas_Island");
        asia.add("Georgia");
        asia.add("Hong_Kong");
        asia.add("India");
        asia.add("Indonesia");
        asia.add("Iran");
        asia.add("Iraq");
        asia.add("Israel");
        asia.add("Japan");
        asia.add("Jordan");
        asia.add("Kazakhstan");
        asia.add("Kuwait");
        asia.add("Kyrgyzstan");
        asia.add("Laos");
        asia.add("Lebanon");
        asia.add("Macao");
        asia.add("Malaysia");
        asia.add("Maldives");
        asia.add("Mongolia");
        asia.add("Myanmar");
        asia.add("Nepal");
        asia.add("North_Korea");
        asia.add("Oman");
        asia.add("Pakistan");
        asia.add("Qatar");
        asia.add("Saudi_Arabia");
        asia.add("Singapore");
        asia.add("South_Georgia");
        asia.add("South_Korea");
        asia.add("Sri_Lanka");
        asia.add("Syria");
        asia.add("Taiwan");
        asia.add("Tajikstan");
        asia.add("Thailand");
        asia.add("Tibet");
        asia.add("Timor-Leste");
        asia.add("Turkey");
        asia.add("Turkmenistan");
        asia.add("UAE");
        asia.add("Uzbekistan");
        asia.add("Vietnam");
        asia.add("Yemen");

        List<String> europe = new ArrayList<String>();
        europe.add("Albania");
        europe.add("Andorra");
        europe.add("Austria");
        europe.add("Belarus");
        europe.add("Belgium");
        europe.add("Bosnia");
        europe.add("Bulgaria");
        europe.add("Croatia");
        europe.add("Cyprus");
        europe.add("Czech_Republic");
        europe.add("Denmark");
        europe.add("Estonia");
        europe.add("Faroe_Islands");
        europe.add("Finland");
        europe.add("France");
        europe.add("Germany");
        europe.add("Gibraltar");
        europe.add("Greece");
        europe.add("Greenland");
        europe.add("Hungary");
        europe.add("Iceland");
        europe.add("Ireland");
        europe.add("Italy");
        europe.add("Latvia");
        europe.add("Liechtenstein");
        europe.add("Lithuania");
        europe.add("Luxembourg");
        europe.add("Macedonia");
        europe.add("Malta");
        europe.add("Moldova");
        europe.add("Monaco");
        europe.add("Netherlands");
        europe.add("Norway");
        europe.add("Poland");
        europe.add("Portugal");
        europe.add("Romania");
        europe.add("Russian_Federation");
        europe.add("San_Marino");
        europe.add("Serbia_and_Motenegro");
        europe.add("Slovakia");
        europe.add("Slovenia");
        europe.add("Soviet_Union");
        europe.add("Spain");
        europe.add("Sweden");
        europe.add("Switzerland");
        europe.add("Ukraine");
        europe.add("United_Kingdom");
        europe.add("Vatican_City");

        List<String> na = new ArrayList<String>();
        na.add("Anguilla");
        na.add("Antigua_and_Barbuda");
        na.add("Aruba");
        na.add("Bahamas");
        na.add("Barbados");
        na.add("Belize");
        na.add("Bermuda");
        na.add("British_Virgin_Islands");
        na.add("Canada");
        na.add("Cayman_Islands");
        na.add("Costa_Rica");
        na.add("Cuba");
        na.add("Dominica");
        na.add("Dominican_Republic");
        na.add("El_Salvador");
        na.add("Grenada");
        na.add("Guatemala");
        na.add("Haiti");
        na.add("Honduras");
        na.add("Jamaica");
        na.add("Marinique");
        na.add("Mexico");
        na.add("Montserrat");
        na.add("Nicaragua");
        na.add("Panama");
        na.add("Puerto_Rico");
        na.add("Saint_Kitts_and_Nevis");
        na.add("Saint_Lucia");
        na.add("Saint_Pierre");
        na.add("St._Vicent_and_Grenadines");
        na.add("Turks_and_Caicos_Islands");
        na.add("United_States_of_America");
        na.add("US_Virgin_Islands");

        List<String> oceania = new ArrayList<String>();
        oceania.add("American_Samoa");
        oceania.add("Australia");
        oceania.add("Cook_Islands");
        oceania.add("Fiji");
        oceania.add("Guam");
        oceania.add("Kribati");
        oceania.add("Marshall Islands");
        oceania.add("Micronesia");
        oceania.add("Nauru");
        oceania.add("New_Zealand");
        oceania.add("Niue");
        oceania.add("Norfolk_Island");
        oceania.add("Palau");
        oceania.add("Papua_New_Guinea");
        oceania.add("Pitcairn_Islands");
        oceania.add("Samoa");
        oceania.add("Soloman_Islands");
        oceania.add("Tonga");
        oceania.add("Tuvalu");
        oceania.add("Vanuatu");
        oceania.add("Wallis_and_Futuna");


        List<String> sa = new ArrayList<String>();
        sa.add("Argentina");
        sa.add("Bolivia");
        sa.add("Brazil");
        sa.add("Chile");
        sa.add("Colombia");
        sa.add("Ecuador");
        sa.add("Falkland_Islands");
        sa.add("French_Polynesia");
        sa.add("Guyana");
        sa.add("Netherlands_Antilles");
        sa.add("Paraguay");
        sa.add("Peru");
        sa.add("Suriname");
        sa.add("Trinidad_and_Tobago");
        sa.add("Uruguay");
        sa.add("Venezuela");


        expandableListDetail.put("Africa",africa);
        expandableListDetail.put("Asia",asia);
        expandableListDetail.put("Europe",europe);
        expandableListDetail.put("North_America",na);
        expandableListDetail.put("Oceania",oceania);
        expandableListDetail.put("South_America",sa);

        return expandableListDetail;
    }
}
